# Generated by Django 3.2.7 on 2021-10-01 16:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='uid',
            field=models.CharField(default=uuid.uuid4, help_text='Укажите UID справочника', max_length=50, unique=True, verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='uid',
            field=models.CharField(default=uuid.uuid4, help_text='Укажите UID элемента справочника', max_length=100, verbose_name='UID'),
        ),
    ]
